name: nuget-ext.yml
on:
  push:
    tags:
      - 'ext-\d+.\d+.\d+' 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build
        run: dotnet build src/CodeOfChaos.Extensions --configuration Release

      - name: Create NuGet package
        run: nuget pack src/CodeOfChaos.Extensions/CodeOfChaos.Extensions.nuspec -OutputDirectory ./nupkgs

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
