name: nuget-ansi.yml
on:
  push:
    tags:
      - 'ansi-\d+.\d+.\d+' 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build src/CodeOfChaos.Ansi --configuration Release

      - name: Publish to NuGet
        run: dotnet nuget push CodeOFChaos.Ansi.nuspec --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
